require('exsqzme/telescope/setup')
require('exsqzme/lsp')
require('exsqzme/completion')
require('exsqzme/luasnip')
require('exsqzme/treesitter')
require('exsqzme/comments')
require('exsqzme/gitsigns')
require('exsqzme/dap')
require('exsqzme/statusline')
-- require('exsqzme/rusttools')
