require('exsqzme/telescope/setup')
require('exsqzme/lsp')
require('exsqzme/completion')
require('exsqzme/luasnip')
require('exsqzme/treesitter')
require('exsqzme/comments')
require('exsqzme/gitsigns')
require('exsqzme/dap')
require('exsqzme/statusline')
require('exsqzme/flutter-tools')
require('exsqzme/colorizer')
require('exsqzme/bufferline')
require('exsqzme/symbols-outline')
require('exsqzme/null-ls')
require('exsqzme/toggleterm')
require('exsqzme/lspsaga')
-- require('exsqzme/rusttools')
